### ISSUE TITLE
How to implement this "speaker diarization" ?

### ISSUE THREAD

**Issue by EMakadiya** [blabbertabber/blabbertabber-ios#1]
Hi @cunnie 

I want the same functionality in my app. So can you please help to suggest something that how can I achieve this?

Can you tell me when you are going to complete this demo?

**Comment by cunnie** [comment]
Hi @EMakadiya ,

Speaker diarization is hard; that's why there are no apps that currently do it.

That being said, my plan is to use the iOS as a recording device (16-bit PCM encoded mono-channel 8kHz sampling, probably compressed to AC3), upload to a linux server that does the actual diarization, and then display the results via the web.

It will be months, years before I complete this "demo".

Here are some sources I've found helpful, and you may want to read them to determine how best to implement speaker diarization:

https://github.com/blabbertabber/blabbertabber#references

Let me know what you accomplish — if you get it working, I'll use your app.

—Brian

**Comment by EMakadiya** [comment]
@cunnie 

Thanks for response. Will try and let you know what my status.

-Ekta
